[tox]
envlist =
    py310-pg29-sa20
    py311-pg29-sa20
    py312-pg29-sa20
    py313-pg29-sa20
    lint
    docs

[testenv]
commands = pytest {posargs} --dbdriver psycopg2 --dbdriver psycopg2cffi --dbdriver redshift_connector
passenv = PGPASSWORD,REDSHIFT_USERNAME,REDSHIFT_HOST,REDSHIFT_PORT,REDSHIFT_DATABASE,REDSHIFT_IAM_ROLE_ARN,AWS_ACCOUNT_ID,REDSHIFT_IAM_ROLE_NAME
deps =
    sa20: sqlalchemy==2.0.48
    pg29: psycopg2-binary==2.9.11
    alembic==1.13.1
    packaging==24.2
    psycopg2cffi==2.9.0
    pytest==8.3.4
    requests==2.32.3
    redshift_connector==2.1.4

[testenv:lint]
deps =
    flake8==7.1.1
    psycopg2-binary
    redshift_connector
commands=flake8 sqlalchemy_redshift tests

[testenv:docs]
changedir=docs
deps=
    -rrequirements-docs.txt
commands=
    sphinx-build -b html -d {envtmpdir}/doctrees . {envtmpdir}/html

[pytest]
addopts = --doctest-modules --doctest-glob='*.rst' --ignore=setup.py --ignore=docs/conf.py
doctest_optionflags = NORMALIZE_WHITESPACE
